#!/bin/bash

# Download/show collection-item
# Usage: discogs_writecustom user-token user-name folder-number release-number instance-number field-id json-string

# json-string must be formated like this: '"01.01.1999"' or if more than one line '"line 1\nline2"'

# from utf-8 file you can make a json-like-string with: cat mytextfile.txt | jq -R -s '.'
# or from a bash-variable with echo "$myvar" | jq -R -s '.'


# scripts returns in stdout/stderr text "SUCCESS" or "ERROR"

# Agent for curl
d_agent="github.com/thgoso/discogs-loader/"
# Discogs-Page
d_userpage="https://api.discogs.com/users"


# Success if curl returns an empty string
ret=$(curl --stderr /dev/null -A "$d_agent" -H "Authorization: Discogs token=$1" -H "Content-Type: application/json" \
  -X POST "$d_userpage/$2/collection/folders/$3/releases/$4/instances/$5/fields/$6" -d "{\"value\":$7}")

if [ -z "$ret" ] ; then
  echo "SUCCESS"
  exit 0
else
  echo "ERROR" >&2
  exit 1
fi
